### ISSUE TITLE
images are missing with the default wikkaedit editor

### ISSUE THREAD

**Issue by hvorragend** [phaidon/Wikula#16]
After installing Wikula from current SVN I see several images missing in the
second bar in the wysiwyg editor:

For example in the Information menuitem -> Wika Name, there is supposed to be an image before that (at least there is a img tag), but this is not there in the install.

modules/wikula/pnincludes/wikkaedit/images/actions/wikkaname.gif
Attachments
Change History
comment:1 Changed 2 years ago by espaan

```
Summary changed from images are missing with the default wakkaedit editor to images are missing with the default wikkaedit editor
```

comment:2 Changed 2 years ago by espaan

Checked out the code and it seems that there might not be images missing,
but the code generates images for all submenu items, even if the images are not htere.

In pnincludes/wikkaedit/wikkaedit.js, line 152 ...

// ===== generate HTML code for toolbar =====
WikkaEdit.prototype.genToolbar = function() {
    // ie6 dosn't understand CSS hover on images, so a JS hack is used
    var ie6_hover = (navigator.userAgent.indexOf("MSIE 6.0") == -1 ? "" : " onmouseover=\"this.className='toolbutton_hover';\" onmouseout=\"this.className='toolbutton_std';\"");

```
// ========== main buttons ==========
var html = "";
for(var i in this.we_buttons) {
    switch (this.we_buttons[i].type) {
        case "button" :     // button
            html += "<img class=\"toolbutton\" src=\""+Wikkaedit_baseURL+"modules/wikula/pnincludes/wikkaedit/images/" + this.refToName(i) + ".gif\" alt=\"" + this.refToName(i) + "\" title=\"" + this.we_buttons[i].title + "\" onclick=\"varWikkaEdit.toolbarButtonClick(this, '" + this.refToName(i) + "');\"" + ie6_hover + " />";
            break;
        case "submenu" :    // submenu
            html += "<img class=\"toolbutton\" src=\""+Wikkaedit_baseURL+"modules/wikula/pnincludes/wikkaedit/images/submenu.gif\" alt=\"submenu\" title=\"" + this.we_buttons[i].title + "\" onclick=\"varWikkaEdit.toolbarButtonClick(this, '" + this.refToName(i) + "');\"" + ie6_hover + " />";
            break;
        case "separator" :  // separator
            html += "<img class=\"toolseparator\" src=\""+Wikkaedit_baseURL+"modules/wikula/pnincludes/wikkaedit/images/separator.gif\" alt=\"|\" />";
            break;
        default :
            alert("genToolbar() : unknown type (" + this.we_buttons[i].type + ")");
    }
}


it might be better to check for the images and only insert if present or remove the images all together. At least in Safari you get empty placeholders for the non existing images.
```

**Comment by phaidon** [comment]
WikkaEdit does not longer exists.
