### ISSUE TITLE
wakkaedit incorrect in IE 7

### ISSUE THREAD

**Issue by hvorragend** [phaidon/Wikula#18]
f you use IE 7 and the wikula edit function including wakkaedit actually the textarea's size is changing always when you select an action from the action dropdown menus...
Attachments
Change History
comment:1 Changed 2 years ago by mateo

Uh
this issue needs to be reported to the editor developers

i plan to work on MultiLanguage? support for that editor
but i don't use IE7 and not an expert on JS issues on IE
so, i hope that they address this issue ;-)
comment:2 Changed 18 months ago by gilles

**Comment by phaidon** [comment]
WakkaEdit does not longer exists.
