### ISSUE TITLE
Backlinks function does not work

### ISSUE THREAD

**Issue by phaidon** [phaidon/Wikula#35]
It always shows that they are no backlings, even if they are.

**Comment by hvorragend** [comment]
Sorry, but it is still not working here.

**Comment by phaidon** [comment]
The backlinks were generated by updating/creating a page. Can you update a page (this one with the link) and check if the problem still exist?

**Comment by phaidon** [comment]
Does this problem still exists?

**Comment by hvorragend** [comment]
I doesn't seem to work, but I cannot do better test at the moment, because LuMicuLa removes a wiki link after the page behind is created.

**Comment by phaidon** [comment]
With Wakka it should work now. With LuMicuLa there is still some work.

**Comment by phaidon** [comment]
Can someone  test it?

@hvorragend

**Comment by hvorragend** [comment]
Sorry, there are some other bugs preventing me to check this issue.

**Comment by phaidon** [comment]
Does this problem still exists?

**Comment by hvorragend** [comment]
No
