### ISSUE TITLE
Format output of title plugin. And change the name?

### ISSUE THREAD

**Issue by hvorragend** [phaidon/Wikula#69]
We should format the output of the plugin for display with DataUtil, because the generated links are causing HTML validation errors.

And what do you think about an other name for this plugin? 'title' is too general and can cause conflicts.

**Comment by phaidon** [comment]
I will change the name.

**Comment by phaidon** [comment]
@hvorragend: Should  I use DataUtil::formatForDisplayHTML?

**Comment by hvorragend** [comment]
Yes, why not.
