### ISSUE TITLE
Error uninstalling Wikula

### ISSUE THREAD

**Issue by hvorragend** [phaidon/Wikula#70]
```
Could not load the 'extensions' module at 'remove'.
Unknown database type longblob requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
```

**Comment by phaidon** [comment]
There should be no longblob. Maybe your database is still from doctrine1 version. Can you remove the module by hand, install it again and test if the install works.

**Comment by hvorragend** [comment]
This WAS a fresh installation of Wikula.
I checked it twice now and I still have this deinstallation error.
After that I have to manually clean up the database each time.

**Comment by phaidon** [comment]
Strange... I cant reproduce it. Can you check in your database which field is a longblob?

**Comment by hvorragend** [comment]
There are no longblob fields in my database.

**Comment by phaidon** [comment]
Maybe it is in another module.

**Comment by hvorragend** [comment]
This could be, because in a clean new Zikula installation I can uninstall the module without an error.

**Comment by hvorragend** [comment]
Got it.  It was caused by an orphaned crpcalendar table in my database.
=> https://github.com/jamiroconca/crpCalendar/issues/1

**Comment by hvorragend** [comment]
https://github.com/zikula/core/issues/220
