### ISSUE TITLE
Add some hints on to be used wiki markup

### ISSUE THREAD

**Issue by espaan** [phaidon/Wikula#79]
Hi,
several wiki modules I have used @ work have pages with help about what to use in the markup for referening to other pages and how to make new ones.

**Comment by phaidon** [comment]
You can add a page by clicking to a non existing page link.

If you search for  a page that does not exists the search page has a link to create the page.

By the way did you activated an editor (Wikka or LuMicuLa)?

**Comment by espaan** [comment]
Hi,
I did not activate the editors, only ckeditor, but that was not handy actually :-)
I meant with help some page on how to insert a page link for creation of new pages. I have a community that might not
know how to make new pages etc. But maybe with one of the editors this is clear.

**Comment by phaidon** [comment]
Without the editor and transform hooks Wikula does not really work. I will add a notice in admin area that the hooks has to be activated.
