### ISSUE TITLE
Edit Page goes on and on preventing saving on changes

### ISSUE THREAD

**Issue by hvorragend** [phaidon/Wikula#9]
On my site i've installed wikula and noticed on big problem. The page i've chosen to edit(in my case the main page) takes me to the edit page which is what i know it should do. But once i'm there the edit page decides to extend on and on and on forever preventing me from saving my changes.

**Comment by phaidon** [comment]
Can somebody reproduce this bug?

@hvorragend: Is that a cozi bug report?

**Comment by hvorragend** [comment]
Yes, this is an old cozi bug report.
